### ISSUE TITLE
Menu on Mobile?

### ISSUE THREAD

**Issue by axel-rank** [tranduyhung/grav-theme-big-picture#10]
Hi,
where's the navigation/menu on mobile devices? If I test various screen sizes in firefox the navigation/menu dissapears...?

**Comment by tranduyhung** [comment]
The menu is hidden on mobile. This is a design from the original HTML template of HTML5Up.

**Comment by haendel-chor** [comment]
Hi,
I understand the logic in it as discussed for example in [modular pages, no menu links in hamburger navigation](https://github.com/getgrav/grav-plugin-admin/issues/421).
But it 'd be indeed very nice to have to opportunity to present a hamburger navigation for mobile devices as for example in the default Quark-Theme of grav.
Is the menu hidden on mobile in the template files of "BigPicture" or already in the original template of HTML5Up? Where would I have to "unhide" this menu (which file, what code) ?
Thanks in advance.

**Comment by tranduyhung** [comment]
There is no menu for mobile for Big Picture HTML template, as you can see at https://html5up.net/big-picture, so this Grav port doesn't have it either. You can create a child theme for this theme and add a mobile menu anywhere you want.
