### ISSUE TITLE
Gallery and Thumbnails

### ISSUE THREAD

**Issue by sugarfunk** [tranduyhung/grav-theme-big-picture#11]
There is something up with the Thumbnail Max width/height setting or I don't understand where the containers are inheriting their settings. 
For example, reducing from 540 (default) to 300 doesn't change the thumbnail container on the site. It does change the resolution of the same size thumbnail. 
**At 250**
![at250](https://user-images.githubusercontent.com/1361962/34009905-b61ef024-e0d8-11e7-8d80-7e82cea1c7d5.png)
**At 540**
![at540](https://user-images.githubusercontent.com/1361962/34009906-b632c054-e0d8-11e7-9a67-4c92e3b1a7b1.png)

**Comment by tranduyhung** [comment]
The value is only used for resizing the thumbnail image files, it doesn't affect anything in the HTML code.
