### ISSUE TITLE
Inheritance - Missing footer

### ISSUE THREAD

**Issue by m4rkinh0** [tranduyhung/grav-theme-big-picture#15]
Hello,
and thank you for this simple Grav theme :)

I am new to Grav and have yet limited knowledge.
I did follow these instructions https://getgrav.org/blog/theme-development-with-inheritance.

Now **my inherited theme do not have any options in Grav's admin panel** (there is not "Big picture" image preview and the only button is to activate the inherited theme), and so, **the resulting website show an empty footer**.

Do you think I missed something or is there work to make the theme "Inheritance compatible" ?
Thank you.

![bigpicture](https://user-images.githubusercontent.com/38053524/40559728-0825c48e-6058-11e8-847e-087935966002.jpg)

All I would like to add to your theme is a way to switch languages with the **[Language Selector](https://github.com/clemdesign/grav-plugin-language-selector)** Plugin

**Comment by tranduyhung** [comment]
It seems you don't have blueprints.yaml which contains theme information and screenshot for back-end's thubmanil, you can copy them from Big Picture theme and edit.

The theme doesn't support Language Selector plugin, you need to implement it by yourself.

**Comment by m4rkinh0** [comment]
Oh wow, **thank you** ! Sorry for my lack of knowledge.

I was able to add the **Language Selector**, but of course I need to learn to adapt the design since it does not fit nicely.
I think this would be a great addition to your "skeleton" theme.
