### ISSUE TITLE
Gallery and image size issues

### ISSUE THREAD

**Issue by huckleberrypie** [tranduyhung/grav-theme-big-picture#16]
Would it be possible to implement better responsive non-gallery image resizing? Like, if I add an image to an info-type section, it bleeds past the info box unless I use the cropResize argument.

Also, is it possible to add support for longer gallery captions and linking to another page in a gallery item, i.e. clicking on the full image leads to another page?

**Comment by tranduyhung** [comment]
Unfortunately the theme doesn't have these features, you need to build them by yourself.
