### ISSUE TITLE
Add reCaptcha

### ISSUE THREAD

**Issue by TwoPlayer** [tranduyhung/grav-theme-big-picture#23]
Is it possible to add reCaptcha to the Form? With the standard reCaptcha integration I get, 2 instead of 1 submit Buttons.
![20-01-2021_10-17-26_firefox](https://user-images.githubusercontent.com/2150354/105153453-bdf8d780-5b08-11eb-876d-eb8639031ad7.png)

**Comment by tranduyhung** [comment]
Please post your page's Markdown code here, I will take a lookk.

**Comment by TwoPlayer** [comment]
I fixed the two Buttons, this was a different Problem, but the Problem which still occurs is, that the Submit Button ignores the Captcha.

This is the page's Markdown code:
`title: Kontakt
heading: 'Schreibe uns.'
form:
  action: /home
  name: contact-form
  fields:
    -
      name: name
      label: Name
      placeholder: Name
      type: text
      validate:
        required: true
    -
      name: email
      label: Email
      placeholder: Email
      type: email
      validate:
        required: true
    -
      name: message
      label: Message
      placeholder: Message
      type: textarea
      rows: 6
      validate:
        required: true
    -
      name: g-recaptcha-response
      label: Captcha
      type: captcha
      recaptcha_site_key: [SITE KEY CENSORED]
      recaptcha_secret_key: [SECRET KEY CENSORED]
      recaptcha_not_validated: 'Captcha ist nicht korrekt!'
      validate:
        required: true
  buttons:
    -
      type: submit
      value: Abschicken
  process:
    -
      email:
        from: '{{ config.plugins.email.from }}'
        to: ['{{ config.plugins.email.to }}']
        subject: '[Kontakformular] Nachricht von {{ form.value.name|e }}'
        body: '{% include ''forms/data.html.twig'' %}'
    -
      save:
        fileprefix: contact-
        dateformat: Ymd-His-u
        extension: txt
        body: '{% include ''forms/data.txt.twig'' %}'
    -
      display: thank-you
`

**Comment by tranduyhung** [comment]
You don't have `captcha: true`
You can find an example here: https://learn.getgrav.org/17/forms/forms/example-form

**Comment by TwoPlayer** [comment]
I tried that, but couldn't fugured out, how to provide the secret there, but i got it now, thank you!
