### ISSUE TITLE
Contact Form Usage

### ISSUE THREAD

**Issue by Dan458** [tranduyhung/grav-theme-big-picture#3]
Hi,

Sorry another usage question. How do you populate fields in the contact form using the admin plugin?

I've added the following using the expert tab in Frontmatter, however noting appears on the fronted :( 

https://gist.github.com/Dan458/dcb1146bc8771e37132428038e65c231

`form:
    name: 'Get In Touch'
    fields:
        -
            name: name
            label: Name
            type: text
            placeholder: 'Enter your name'
            autofocus: 'on'
            autocomplete: 'on'
        -
            name: email
            label: 'E-mail Address'
            type: email
            validate:
                required: true
        -
            name: textarea
            type: textarea
            label: 'Your Message'
            placeholder: 'Enter your message'
        -
            name: spacer
            type: spacer
            break: true
    buttons:
        -
            type: submit
            value: Submit
        -
            type: reset
            value: Reset
    process:
        -
            email:
                subject: ' Contact - {{ form.value.name|e }}'
                body: '{% include ''forms/data.html.twig'' %}'
        -
            message: 'Thank you for getting in touch, we will contact you as soon as possible'
        -
            display: thanks`

Regards,
Dan

**Comment by tranduyhung** [comment]
Hi Dan,

What file do you put this code in?

It should be in your homepage's file, like this: https://raw.githubusercontent.com/tranduyhung/grav-skeleton-big-picture/master/pages/01.home/modular.md

The form is shown in the module page which has contact.md file.

You can check the files in the theme's skeletons as example: https://github.com/tranduyhung/grav-skeleton-big-picture/tree/master/pages/01.home

Regards,
Hung

**Comment by Dan458** [comment]
Ah that skeleton cleared things up, yes i'de put the code in the wrong place, putting it in the contact from rather than the modular.md

However now that i've added that to the bottom of modular.md the form no longer sticks to the footer and has the rising animation.

AH! -- i must have made an error somewhere else. 

Regards,
Dan

**Comment by Dan458** [comment]
meh, using your Skeleton and copying the setting from the them has sorted it. Im happy :)

Thanks for your continued support
