### ISSUE TITLE
Gallery Lightbox not working. 

### ISSUE THREAD

**Issue by grobisesam86** [tranduyhung/grav-theme-big-picture#31]
There seems to be a jquery conflict with the gallery option. When trying to open a picture in Lightbox the following error hits:
`jquery-3.x.min.js:2 Uncaught TypeError: e.indexOf is not a function` error in jquery-3.x.min.js 

Check https://odenwald-trekking.de/ for replicating the error. 

I already fixed a line in your jquery main.js file that triggered the same error in console.

`				.load(function() {
					$window.trigger('resize');
				});`

Line 227. It should be.

				`.on('load',` function() {
					$window.trigger('resize');
				});`

In the end, I'm not sure why, but on your demo site the gallery uses jquery 2.x instead of 3.x. Testing it, I found the ancient 2.x version works fine, so I figured this is a theme problem, rather than a system problem.

It'd be nice, if you could take a look at it. Cheers and thank you!

Kind regards

And thanks for making this theme! It's very nice, very easy to use and just perfekt for a landing page!

**Comment by tranduyhung** [comment]
Thank you for reporting this! I updated the theme from its original source and this problem was fixed.
