### ISSUE TITLE
Customizations : box transparency and padding

### ISSUE THREAD

**Issue by papageno75** [tranduyhung/grav-theme-big-picture#32]
Hi, 

First of all, thx a lot for your work. Big-Picture works great and is elegant and simple, exactly what I'm looking for.

I would like to customize the box color/transparency and some padding. I tried to modify `_box.scss` located in `/assets/scss/components` without any success. I also tried `main.css` in `/assets/css`.

I would be grateful if you could help me to achieve these customization.

Sorry if my question seems ridiculous, web-designing is completely new for me.

Thx for your help !

**Comment by tranduyhung** [comment]
After editing the SCSS file you need to compile assets/sass/main.scss to assets/css/main.css. You can learn more about SASS at https://sass-lang.com/guide.
