### ISSUE TITLE
Background Image option is not visible in Content tab for intro and info page file.

### ISSUE THREAD

**Issue by DrkManix** [tranduyhung/grav-theme-big-picture#33]
Hi,
I'm struggling to figure out how to pass my images as a background image for those sections.

that is the exemple i get in the readme:
![tutorial_2](https://user-images.githubusercontent.com/45601260/182365948-cf3420de-8dd5-436c-9f5a-4f5aaf058367.jpg)

and that is what i actually get:
![myscreenshot_2](https://user-images.githubusercontent.com/45601260/182366037-d708aba9-a6d3-4311-b5f6-4b7dba1040f4.jpg)

Am i missing something or does the feature was removed?
Thank you in advance

**Comment by tranduyhung** [comment]
Ensure that your page uses `intro` template. The fields are still available.

![screenshot-localhost_8044-2022 08 02-18_46_59](https://user-images.githubusercontent.com/503262/182367215-3cbe55e6-f962-4007-a3c3-7bb888ebef73.png)

**Comment by DrkManix** [comment]
![myscreenshot_3](https://user-images.githubusercontent.com/45601260/182370206-8eaf0107-f94d-4ea3-8ee7-e957d687c24c.jpg)

It does uses it

**Comment by tranduyhung** [comment]
Is the activated theme really `Big Picture`? With the latest version of `Grav` (v1.7.34) and `Admin` plugin (v1.10.34) I can't reproduce the problem.

**Comment by DrkManix** [comment]
The activated theme is Big Picture v2.0.0, Grav v1.7.34; Admin v1.10.34

**Comment by tranduyhung** [comment]
Your only solution for now is adding the background image option to the Markdown content, here is an example: https://raw.githubusercontent.com/tranduyhung/grav-skeleton-big-picture/master/pages/01.home/_intro/intro.md

**Comment by DrkManix** [comment]
It worked great ! Thank you so much for your time and reactivity !
