### ISSUE TITLE
'Uncaught ReferenceError: breakpoints is not defined' after updating

### ISSUE THREAD

**Issue by lguariento** [tranduyhung/grav-theme-big-picture#34]
Hello, I just updated from version 1.x to 2.x and the website doesn't look right (the 'jump to' sections is not smooth, and the fonts and images look wonky).

I get this error on the console:

```
Uncaught ReferenceError: breakpoints is not defined
    <anonymous> .../user/themes/big-picture/assets/js/main.js:15
    <anonymous> .../user/themes/big-picture/assets/js/main.js:219
[main.js:15:3](.../user/themes/big-picture/assets/js/main.js)
```

**Comment by tranduyhung** [comment]
breakpoints is defined in [assets/js/breakpoints.min.js](https://github.com/tranduyhung/grav-theme-big-picture/blob/master/assets/js/breakpoints.min.js) and is loaded in [templates/partials/head.html.twig](https://github.com/tranduyhung/grav-theme-big-picture/blob/7a552bceb2fb6997443824c070a47d47b73a9a5f/templates/partials/head.html.twig#L36). Did you try to clear your browser and Grav's cache? Can you check that breakpoints.min.js is loaded on your site?

**Comment by lguariento** [comment]
Thank you very much for this, since I use a custom theme, extending this one, I didn't have the linecalling the .js in my custom head. Problem solved.
