### ISSUE TITLE
No Background Image input box

### ISSUE THREAD

**Issue by SomeonegetaDev** [tranduyhung/grav-theme-big-picture#35]
Greetings, when reading the directions I've come to notice that the " background image input box" is not displaying on the info, intro content area at the bottom. I tried 2 different browser edge and Mozilla and neither are displaying this most important feature.

**Comment by tranduyhung** [comment]
Could you please attach a screenshot of the input box you mentioned?

**Comment by SomeonegetaDev** [comment]
I've abandoned grav completely and deleted it from my server. Thank you for the reply.

**Comment by SomeonegetaDev** [comment]
Here is the screenshot
https://imgur.com/sq2J7Pu

**Comment by bitstarr** [comment]
The blueprint is invalid. You need to set some quotation marks around the value (string).
![](https://user-images.githubusercontent.com/3891444/196809351-2769ad9f-892a-4468-a178-e215ea79fab8.png)

**Comment by SomeonegetaDev** [comment]
Thank you !

**Comment by Didaktik-digital** [comment]
Hi there,
I am facing the same issue.
Setup:
Grav v1.7.37.1 - Admin v1.10.37.1 - Form 7.1.1
When adding the modules Intro and Info, there is no Background image box in the content section of the module.
There is: Title, Text Editor, Page Media, Home Menu Item and After Safe.

Please let me know if more information is needed.

**Comment by tranduyhung** [comment]
@Didaktik-digital You can apply the solution above, or update to version 2.0.1.
