### ISSUE TITLE
Can`t change the image

### ISSUE THREAD

**Issue by ashraf21c** [tranduyhung/grav-theme-big-picture#40]
Hello,
(1) I have the admin plugin, but I have 'Security" tab instead of "Images" tab.
     Can`t locate "Images" tab anywhere.
(2) I tried to replace it using FTP (maintaining same file name), but I couldn`t find it.

**Comment by tranduyhung** [comment]
`Images` tab is only available for `gallery` template. Ensure that your page uses that template.

**Comment by ashraf21c** [comment]
Under Adanced/Page Templates there is no "Gallery" option.
I use Big Picture theme.
In fact, I downloaded the full Skelton.

**Comment by tranduyhung** [comment]
![screenshot-localhost_8001-2024 01 17-21_28_42](https://github.com/tranduyhung/grav-theme-big-picture/assets/503262/8a686795-cab4-4a5d-af5f-a2eea0a17e64)

**Comment by ashraf21c** [comment]
I am not near a PC now, but this is the same.. no gallery option.

![Screenshot_٢٠٢٤٠١١٧_٢٠١١٤٦_Samsung Internet Beta](https://github.com/tranduyhung/grav-theme-big-picture/assets/38018061/50a23c7d-ab2e-4eea-9a97-d7528afe0585)

**Comment by tranduyhung** [comment]
I confirm that the `gallery` template is available there in the latest version of Grav. Check your whole configuration again.
