### ISSUE TITLE
Accordion plugin isn1t compatible with TinyMCE

### ISSUE THREAD

**Issue by ashraf21c** [tranduyhung/grav-theme-big-picture#42]
Hello,
I set up accordion functionality in TinyMCE plugin.
However, in the editor, I get this error:
Failed to load plugin: accordion from url https://prize-sci.org/fest/user/plugins/tinymce-editor/js/tinymce/plugins/accordion/plugin.min.js

P.S. This functionality is compatible with version 6 only of tinymce.

**Comment by tranduyhung** [comment]
Please contact the author of that "accordion function" or TinyMCE plugin. This is the repository for Big Picture theme, it has nothing to do these with those plugins.

**Comment by ashraf21c** [comment]
> Please contact the author of that "accordion function" or TinyMCE plugin. This is the repository for Big Picture theme, it has nothing to do these with those plugins.

I didn`t notice these being separate repositories.. sorry, thank you.
