### ISSUE TITLE
Grav plugins integration

### ISSUE THREAD

**Issue by Tokay-tech** [tranduyhung/grav-theme-big-picture#7]
For plugins compatibility is needed to load jquery with a priority (issue found with lightslider plugin).
My solution: 
in file templates/partials/header.html.twig row 43
```
 -  {% do assets.add('theme://assets/js/jquery.min.js') %}
 +  {% do assets.add('theme://assets/js/jquery.min.js', 100) %}
```

**Comment by tranduyhung** [comment]
Thank you for this suggestion, it was implemented in 1.0.4.
